program Dialog;
var
  S, S1, S2: string;
begin
  writeln('Good day!');
  writeln('What is your name?');
  readln(S);
  writeln('My name is K4 and I am 103 years old.');
  writeln(S, ', Interesting, what do you like to read?');
  readln(S1);
  writeln('I love to read anything.');
  writeln('What do you do or enjoy doing in your free time?');
  readln(S2);
  writeln(S2, ' What is your favorite season? And why?');
  writeln('I am in a hurry. It was nice talking to you. See you later!');
  readln;
end.

